name: build

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build.yml"
      - "**.zig"
      - "**.zon"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "**.zig"
      - "**.zon"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            target: x86_64-linux-musl
            zig-version: master
          - os: macos-latest
            platform: macos
            target: aarch64-macos
            zig-version: master
          - os: windows-latest
            platform: windows
            target: x86_64-windows-gnu
            zig-version: master

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Grab Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Install sqlite (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y sqlite3

      - name: Install sqlite (macOS)
        if: runner.os == 'macOS'
        run: brew install sqlite

      - name: Install sqlite (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: winget install --id SQLite.sqlite -e --accept-source-agreements --accept-package-agreements

      - name: Build ${{ matrix.platform }}
        run: zig build -Dtarget=${{ matrix.target }}
